// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: player.proto

package proto;

public final class ProtoPlayer {
  private ProtoPlayer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageHeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .proto.MessageHeader.Type messageType = 1;
    boolean hasMessageType();
    proto.ProtoPlayer.MessageHeader.Type getMessageType();
  }
  public static final class MessageHeader extends
      com.google.protobuf.GeneratedMessage
      implements MessageHeaderOrBuilder {
    // Use MessageHeader.newBuilder() to construct.
    private MessageHeader(Builder builder) {
      super(builder);
    }
    private MessageHeader(boolean noInit) {}
    
    private static final MessageHeader defaultInstance;
    public static MessageHeader getDefaultInstance() {
      return defaultInstance;
    }
    
    public MessageHeader getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.ProtoPlayer.internal_static_proto_MessageHeader_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.ProtoPlayer.internal_static_proto_MessageHeader_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      COMMAND(0, 1),
      ;
      
      public static final int COMMAND_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 1: return COMMAND;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return proto.ProtoPlayer.MessageHeader.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        COMMAND, 
      };
      
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:proto.MessageHeader.Type)
    }
    
    private int bitField0_;
    // required .proto.MessageHeader.Type messageType = 1;
    public static final int MESSAGETYPE_FIELD_NUMBER = 1;
    private proto.ProtoPlayer.MessageHeader.Type messageType_;
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public proto.ProtoPlayer.MessageHeader.Type getMessageType() {
      return messageType_;
    }
    
    private void initFields() {
      messageType_ = proto.ProtoPlayer.MessageHeader.Type.COMMAND;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMessageType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, messageType_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, messageType_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static proto.ProtoPlayer.MessageHeader parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.ProtoPlayer.MessageHeader parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.ProtoPlayer.MessageHeader parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.ProtoPlayer.MessageHeader parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.ProtoPlayer.MessageHeader parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.ProtoPlayer.MessageHeader parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.ProtoPlayer.MessageHeader parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.ProtoPlayer.MessageHeader parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.ProtoPlayer.MessageHeader parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.ProtoPlayer.MessageHeader parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.ProtoPlayer.MessageHeader prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements proto.ProtoPlayer.MessageHeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.ProtoPlayer.internal_static_proto_MessageHeader_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.ProtoPlayer.internal_static_proto_MessageHeader_fieldAccessorTable;
      }
      
      // Construct using proto.ProtoPlayer.MessageHeader.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        messageType_ = proto.ProtoPlayer.MessageHeader.Type.COMMAND;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.ProtoPlayer.MessageHeader.getDescriptor();
      }
      
      public proto.ProtoPlayer.MessageHeader getDefaultInstanceForType() {
        return proto.ProtoPlayer.MessageHeader.getDefaultInstance();
      }
      
      public proto.ProtoPlayer.MessageHeader build() {
        proto.ProtoPlayer.MessageHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private proto.ProtoPlayer.MessageHeader buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        proto.ProtoPlayer.MessageHeader result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public proto.ProtoPlayer.MessageHeader buildPartial() {
        proto.ProtoPlayer.MessageHeader result = new proto.ProtoPlayer.MessageHeader(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.messageType_ = messageType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.ProtoPlayer.MessageHeader) {
          return mergeFrom((proto.ProtoPlayer.MessageHeader)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(proto.ProtoPlayer.MessageHeader other) {
        if (other == proto.ProtoPlayer.MessageHeader.getDefaultInstance()) return this;
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMessageType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              proto.ProtoPlayer.MessageHeader.Type value = proto.ProtoPlayer.MessageHeader.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                messageType_ = value;
              }
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .proto.MessageHeader.Type messageType = 1;
      private proto.ProtoPlayer.MessageHeader.Type messageType_ = proto.ProtoPlayer.MessageHeader.Type.COMMAND;
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public proto.ProtoPlayer.MessageHeader.Type getMessageType() {
        return messageType_;
      }
      public Builder setMessageType(proto.ProtoPlayer.MessageHeader.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        messageType_ = value;
        onChanged();
        return this;
      }
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = proto.ProtoPlayer.MessageHeader.Type.COMMAND;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:proto.MessageHeader)
    }
    
    static {
      defaultInstance = new MessageHeader(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.MessageHeader)
  }
  
  public interface CommandOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .proto.Command.Type type = 1;
    boolean hasType();
    proto.ProtoPlayer.Command.Type getType();
    
    // optional .proto.Command.Information info = 2;
    boolean hasInfo();
    proto.ProtoPlayer.Command.Information getInfo();
    proto.ProtoPlayer.Command.InformationOrBuilder getInfoOrBuilder();
  }
  public static final class Command extends
      com.google.protobuf.GeneratedMessage
      implements CommandOrBuilder {
    // Use Command.newBuilder() to construct.
    private Command(Builder builder) {
      super(builder);
    }
    private Command(boolean noInit) {}
    
    private static final Command defaultInstance;
    public static Command getDefaultInstance() {
      return defaultInstance;
    }
    
    public Command getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.ProtoPlayer.internal_static_proto_Command_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.ProtoPlayer.internal_static_proto_Command_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      NONE(0, 1),
      SET_POSITION(1, 2),
      PREVIOUS(2, 3),
      NEXT(3, 4),
      BACKWARD(4, 5),
      FORWARD(5, 6),
      STOP(6, 7),
      PLAY(7, 8),
      PAUSE(8, 9),
      MUTE(9, 10),
      SET_VOLUME(10, 11),
      TOGGLE_FULL_SCREEN(11, 12),
      START_MOVIE(12, 13),
      ;
      
      public static final int NONE_VALUE = 1;
      public static final int SET_POSITION_VALUE = 2;
      public static final int PREVIOUS_VALUE = 3;
      public static final int NEXT_VALUE = 4;
      public static final int BACKWARD_VALUE = 5;
      public static final int FORWARD_VALUE = 6;
      public static final int STOP_VALUE = 7;
      public static final int PLAY_VALUE = 8;
      public static final int PAUSE_VALUE = 9;
      public static final int MUTE_VALUE = 10;
      public static final int SET_VOLUME_VALUE = 11;
      public static final int TOGGLE_FULL_SCREEN_VALUE = 12;
      public static final int START_MOVIE_VALUE = 13;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 1: return NONE;
          case 2: return SET_POSITION;
          case 3: return PREVIOUS;
          case 4: return NEXT;
          case 5: return BACKWARD;
          case 6: return FORWARD;
          case 7: return STOP;
          case 8: return PLAY;
          case 9: return PAUSE;
          case 10: return MUTE;
          case 11: return SET_VOLUME;
          case 12: return TOGGLE_FULL_SCREEN;
          case 13: return START_MOVIE;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return proto.ProtoPlayer.Command.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        NONE, SET_POSITION, PREVIOUS, NEXT, BACKWARD, FORWARD, STOP, PLAY, PAUSE, MUTE, SET_VOLUME, TOGGLE_FULL_SCREEN, START_MOVIE, 
      };
      
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:proto.Command.Type)
    }
    
    public interface InformationOrBuilder
        extends com.google.protobuf.MessageOrBuilder {
      
      // required string value = 1;
      boolean hasValue();
      String getValue();
    }
    public static final class Information extends
        com.google.protobuf.GeneratedMessage
        implements InformationOrBuilder {
      // Use Information.newBuilder() to construct.
      private Information(Builder builder) {
        super(builder);
      }
      private Information(boolean noInit) {}
      
      private static final Information defaultInstance;
      public static Information getDefaultInstance() {
        return defaultInstance;
      }
      
      public Information getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.ProtoPlayer.internal_static_proto_Command_Information_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.ProtoPlayer.internal_static_proto_Command_Information_fieldAccessorTable;
      }
      
      private int bitField0_;
      // required string value = 1;
      public static final int VALUE_FIELD_NUMBER = 1;
      private java.lang.Object value_;
      public boolean hasValue() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getValue() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          return (String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (com.google.protobuf.Internal.isValidUtf8(bs)) {
            value_ = s;
          }
          return s;
        }
      }
      private com.google.protobuf.ByteString getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8((String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      
      private void initFields() {
        value_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        if (!hasValue()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getValueBytes());
        }
        getUnknownFields().writeTo(output);
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getValueBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static proto.ProtoPlayer.Command.Information parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static proto.ProtoPlayer.Command.Information parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static proto.ProtoPlayer.Command.Information parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static proto.ProtoPlayer.Command.Information parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static proto.ProtoPlayer.Command.Information parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static proto.ProtoPlayer.Command.Information parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static proto.ProtoPlayer.Command.Information parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static proto.ProtoPlayer.Command.Information parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static proto.ProtoPlayer.Command.Information parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static proto.ProtoPlayer.Command.Information parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(proto.ProtoPlayer.Command.Information prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements proto.ProtoPlayer.Command.InformationOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return proto.ProtoPlayer.internal_static_proto_Command_Information_descriptor;
        }
        
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return proto.ProtoPlayer.internal_static_proto_Command_Information_fieldAccessorTable;
        }
        
        // Construct using proto.ProtoPlayer.Command.Information.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private Builder(BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          value_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return proto.ProtoPlayer.Command.Information.getDescriptor();
        }
        
        public proto.ProtoPlayer.Command.Information getDefaultInstanceForType() {
          return proto.ProtoPlayer.Command.Information.getDefaultInstance();
        }
        
        public proto.ProtoPlayer.Command.Information build() {
          proto.ProtoPlayer.Command.Information result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private proto.ProtoPlayer.Command.Information buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          proto.ProtoPlayer.Command.Information result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public proto.ProtoPlayer.Command.Information buildPartial() {
          proto.ProtoPlayer.Command.Information result = new proto.ProtoPlayer.Command.Information(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.value_ = value_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }
        
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof proto.ProtoPlayer.Command.Information) {
            return mergeFrom((proto.ProtoPlayer.Command.Information)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }
        
        public Builder mergeFrom(proto.ProtoPlayer.Command.Information other) {
          if (other == proto.ProtoPlayer.Command.Information.getDefaultInstance()) return this;
          if (other.hasValue()) {
            setValue(other.getValue());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }
        
        public final boolean isInitialized() {
          if (!hasValue()) {
            
            return false;
          }
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder(
              this.getUnknownFields());
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  this.setUnknownFields(unknownFields.build());
                  onChanged();
                  return this;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                value_ = input.readBytes();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // required string value = 1;
        private java.lang.Object value_ = "";
        public boolean hasValue() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public String getValue() {
          java.lang.Object ref = value_;
          if (!(ref instanceof String)) {
            String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
            value_ = s;
            return s;
          } else {
            return (String) ref;
          }
        }
        public Builder setValue(String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          value_ = value;
          onChanged();
          return this;
        }
        public Builder clearValue() {
          bitField0_ = (bitField0_ & ~0x00000001);
          value_ = getDefaultInstance().getValue();
          onChanged();
          return this;
        }
        void setValue(com.google.protobuf.ByteString value) {
          bitField0_ |= 0x00000001;
          value_ = value;
          onChanged();
        }
        
        // @@protoc_insertion_point(builder_scope:proto.Command.Information)
      }
      
      static {
        defaultInstance = new Information(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:proto.Command.Information)
    }
    
    private int bitField0_;
    // required .proto.Command.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private proto.ProtoPlayer.Command.Type type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public proto.ProtoPlayer.Command.Type getType() {
      return type_;
    }
    
    // optional .proto.Command.Information info = 2;
    public static final int INFO_FIELD_NUMBER = 2;
    private proto.ProtoPlayer.Command.Information info_;
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public proto.ProtoPlayer.Command.Information getInfo() {
      return info_;
    }
    public proto.ProtoPlayer.Command.InformationOrBuilder getInfoOrBuilder() {
      return info_;
    }
    
    private void initFields() {
      type_ = proto.ProtoPlayer.Command.Type.NONE;
      info_ = proto.ProtoPlayer.Command.Information.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasInfo()) {
        if (!getInfo().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, info_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, info_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static proto.ProtoPlayer.Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.ProtoPlayer.Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.ProtoPlayer.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static proto.ProtoPlayer.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static proto.ProtoPlayer.Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.ProtoPlayer.Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static proto.ProtoPlayer.Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.ProtoPlayer.Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static proto.ProtoPlayer.Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static proto.ProtoPlayer.Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.ProtoPlayer.Command prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements proto.ProtoPlayer.CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.ProtoPlayer.internal_static_proto_Command_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.ProtoPlayer.internal_static_proto_Command_fieldAccessorTable;
      }
      
      // Construct using proto.ProtoPlayer.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInfoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = proto.ProtoPlayer.Command.Type.NONE;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (infoBuilder_ == null) {
          info_ = proto.ProtoPlayer.Command.Information.getDefaultInstance();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.ProtoPlayer.Command.getDescriptor();
      }
      
      public proto.ProtoPlayer.Command getDefaultInstanceForType() {
        return proto.ProtoPlayer.Command.getDefaultInstance();
      }
      
      public proto.ProtoPlayer.Command build() {
        proto.ProtoPlayer.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private proto.ProtoPlayer.Command buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        proto.ProtoPlayer.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public proto.ProtoPlayer.Command buildPartial() {
        proto.ProtoPlayer.Command result = new proto.ProtoPlayer.Command(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (infoBuilder_ == null) {
          result.info_ = info_;
        } else {
          result.info_ = infoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.ProtoPlayer.Command) {
          return mergeFrom((proto.ProtoPlayer.Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(proto.ProtoPlayer.Command other) {
        if (other == proto.ProtoPlayer.Command.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasInfo()) {
          mergeInfo(other.getInfo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasInfo()) {
          if (!getInfo().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              proto.ProtoPlayer.Command.Type value = proto.ProtoPlayer.Command.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              proto.ProtoPlayer.Command.Information.Builder subBuilder = proto.ProtoPlayer.Command.Information.newBuilder();
              if (hasInfo()) {
                subBuilder.mergeFrom(getInfo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setInfo(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .proto.Command.Type type = 1;
      private proto.ProtoPlayer.Command.Type type_ = proto.ProtoPlayer.Command.Type.NONE;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public proto.ProtoPlayer.Command.Type getType() {
        return type_;
      }
      public Builder setType(proto.ProtoPlayer.Command.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = proto.ProtoPlayer.Command.Type.NONE;
        onChanged();
        return this;
      }
      
      // optional .proto.Command.Information info = 2;
      private proto.ProtoPlayer.Command.Information info_ = proto.ProtoPlayer.Command.Information.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          proto.ProtoPlayer.Command.Information, proto.ProtoPlayer.Command.Information.Builder, proto.ProtoPlayer.Command.InformationOrBuilder> infoBuilder_;
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public proto.ProtoPlayer.Command.Information getInfo() {
        if (infoBuilder_ == null) {
          return info_;
        } else {
          return infoBuilder_.getMessage();
        }
      }
      public Builder setInfo(proto.ProtoPlayer.Command.Information value) {
        if (infoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          info_ = value;
          onChanged();
        } else {
          infoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setInfo(
          proto.ProtoPlayer.Command.Information.Builder builderForValue) {
        if (infoBuilder_ == null) {
          info_ = builderForValue.build();
          onChanged();
        } else {
          infoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeInfo(proto.ProtoPlayer.Command.Information value) {
        if (infoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              info_ != proto.ProtoPlayer.Command.Information.getDefaultInstance()) {
            info_ =
              proto.ProtoPlayer.Command.Information.newBuilder(info_).mergeFrom(value).buildPartial();
          } else {
            info_ = value;
          }
          onChanged();
        } else {
          infoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearInfo() {
        if (infoBuilder_ == null) {
          info_ = proto.ProtoPlayer.Command.Information.getDefaultInstance();
          onChanged();
        } else {
          infoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public proto.ProtoPlayer.Command.Information.Builder getInfoBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getInfoFieldBuilder().getBuilder();
      }
      public proto.ProtoPlayer.Command.InformationOrBuilder getInfoOrBuilder() {
        if (infoBuilder_ != null) {
          return infoBuilder_.getMessageOrBuilder();
        } else {
          return info_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          proto.ProtoPlayer.Command.Information, proto.ProtoPlayer.Command.Information.Builder, proto.ProtoPlayer.Command.InformationOrBuilder> 
          getInfoFieldBuilder() {
        if (infoBuilder_ == null) {
          infoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              proto.ProtoPlayer.Command.Information, proto.ProtoPlayer.Command.Information.Builder, proto.ProtoPlayer.Command.InformationOrBuilder>(
                  info_,
                  getParentForChildren(),
                  isClean());
          info_ = null;
        }
        return infoBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:proto.Command)
    }
    
    static {
      defaultInstance = new Command(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:proto.Command)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MessageHeader_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_MessageHeader_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Command_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_Command_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Command_Information_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_proto_Command_Information_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014player.proto\022\005proto\"T\n\rMessageHeader\022." +
      "\n\013messageType\030\001 \002(\0162\031.proto.MessageHeade" +
      "r.Type\"\023\n\004Type\022\013\n\007COMMAND\020\001\"\256\002\n\007Command\022" +
      "!\n\004type\030\001 \002(\0162\023.proto.Command.Type\022(\n\004in" +
      "fo\030\002 \001(\0132\032.proto.Command.Information\032\034\n\013" +
      "Information\022\r\n\005value\030\001 \002(\t\"\267\001\n\004Type\022\010\n\004N" +
      "ONE\020\001\022\020\n\014SET_POSITION\020\002\022\014\n\010PREVIOUS\020\003\022\010\n" +
      "\004NEXT\020\004\022\014\n\010BACKWARD\020\005\022\013\n\007FORWARD\020\006\022\010\n\004ST" +
      "OP\020\007\022\010\n\004PLAY\020\010\022\t\n\005PAUSE\020\t\022\010\n\004MUTE\020\n\022\016\n\nS" +
      "ET_VOLUME\020\013\022\026\n\022TOGGLE_FULL_SCREEN\020\014\022\017\n\013S",
      "TART_MOVIE\020\rB\rB\013ProtoPlayer"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_proto_MessageHeader_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_proto_MessageHeader_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_MessageHeader_descriptor,
              new java.lang.String[] { "MessageType", },
              proto.ProtoPlayer.MessageHeader.class,
              proto.ProtoPlayer.MessageHeader.Builder.class);
          internal_static_proto_Command_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_proto_Command_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_Command_descriptor,
              new java.lang.String[] { "Type", "Info", },
              proto.ProtoPlayer.Command.class,
              proto.ProtoPlayer.Command.Builder.class);
          internal_static_proto_Command_Information_descriptor =
            internal_static_proto_Command_descriptor.getNestedTypes().get(0);
          internal_static_proto_Command_Information_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_proto_Command_Information_descriptor,
              new java.lang.String[] { "Value", },
              proto.ProtoPlayer.Command.Information.class,
              proto.ProtoPlayer.Command.Information.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
